### ISSUE TITLE
is this still an active project?

### ISSUE THREAD

**Issue by trungpham** [xcambar/n-ext#3]
I really love the idea of sharing the model code between the client and the server!

Just want to know what the state of this project. Is it stable enough to be used in production?

Or is there another similar project like this that is more active?

Thanks.

**Comment by xcambar** [comment]
Thanks for the comment.

The project _was_ usable with Node 0.4, but as told in issue #2, the changes in require.paths in Node >0.4 require an update. As I got numerous requests to update the project, I plan to have it fixed by the end of the week.

To be honest, the project has not be thoroughly tested, I've just put it to work on small- to mid-size projects, but it worked gracefully for me. I invite you to try it now or as soon as fixed for Node 0.6 (as preferred) and provide me with feedback.

AFAIK, there's no other public project with a similar goal.
